import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:intl/intl.dart';
import '../../../core/l10n/content_localizations.dart';
import '../../../core/services/storage_service.dart';
import '../../../core/theme/app_colors.dart';
import '../consult_config.dart';
import '../consult_provider.dart';
import '../models/consultation.dart';

/// One consultation thread — shared by the parent and the doctor.
/// Whose-side a bubble sits on depends on who is viewing.
class ConsultThreadScreen extends ConsumerStatefulWidget {
  final String consultId;
  const ConsultThreadScreen({super.key, required this.consultId});

  @override
  ConsumerState<ConsultThreadScreen> createState() =>
      _ConsultThreadScreenState();
}

class _ConsultThreadScreenState extends ConsumerState<ConsultThreadScreen> {
  final _controller = TextEditingController();
  bool _sending = false;

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  Future<void> _send({File? photo}) async {
    final text = _controller.text.trim();
    if (text.isEmpty && photo == null) return;
    setState(() => _sending = true);
    _controller.clear();
    final ok = await ref.read(consultServiceProvider).sendMessage(
          widget.consultId,
          text: text,
          fromDoctor: isDoctorAccount,
          photo: photo,
        );
    if (!mounted) return;
    setState(() => _sending = false);
    if (!ok) {
      ScaffoldMessenger.of(context).showSnackBar(SnackBar(
        content: Text(tr(currentLang(context),
            en: 'Could not send. Try again.',
            ru: 'Не удалось отправить. Попробуй ещё раз.',
            ky: 'Жөнөтүлгөн жок. Кайра аракет кыл.')),
      ));
    }
  }

  Future<void> _attachPhoto() async {
    final file = await StorageService().showPickerSheet(context);
    if (file != null) await _send(photo: file);
  }

  void _sendFollowUp(String text) {
    if (text.isEmpty) return;
    _controller.text = text;
    _send();
  }

  @override
  Widget build(BuildContext context) {
    final messages = ref.watch(consultMessagesProvider(widget.consultId));
    final consult = ref.watch(consultationProvider(widget.consultId)).asData?.value;
    final lang = currentLang(context);
    final isDoctor = isDoctorAccount;

    return Scaffold(
      backgroundColor: AppColors.background,
      appBar: AppBar(
        title: Text(isDoctor
            ? tr(lang, en: 'Consultation', ru: 'Консультация', ky: 'Консультация')
            : kDoctorName),
      ),
      body: Column(
        children: [
          // Doctor-only briefing card pinned to the top of the thread.
          // The brief is server-generated by generateDoctorBrief shortly
          // after consult creation; while it's composing, nothing is
          // shown (the thread itself is still readable).
          if (isDoctor && consult?.doctorBriefSummary != null)
            _BriefCard(brief: consult!.doctorBriefSummary!, lang: lang),
          Expanded(
            child: messages.when(
              loading: () =>
                  const Center(child: CircularProgressIndicator()),
              error: (_, _) => Center(
                child: Text(tr(lang,
                    en: 'Could not load the thread.',
                    ru: 'Не удалось загрузить переписку.',
                    ky: 'Жазышуу жүктөлгөн жок.')),
              ),
              data: (msgs) => msgs.isEmpty
                  ? const SizedBox.shrink()
                  : ListView.builder(
                      reverse: true,
                      padding: const EdgeInsets.fromLTRB(12, 12, 12, 12),
                      itemCount: msgs.length,
                      itemBuilder: (context, i) {
                        final m = msgs[msgs.length - 1 - i];
                        if (m.kind == ConsultMessageKind.aiFollowupSuggestion) {
                          // Parents see the follow-up pills; doctors don't.
                          if (isDoctor) return const SizedBox.shrink();
                          return _FollowUpPills(
                            suggestions: m.suggestedFollowUps,
                            onTap: _sendFollowUp,
                            lang: lang,
                          );
                        }
                        return _Bubble(
                          message: m,
                          mine: m.fromDoctor == isDoctor,
                        );
                      },
                    ),
            ),
          ),
          _Composer(
            controller: _controller,
            sending: _sending,
            onSend: () => _send(),
            onAttach: _attachPhoto,
            hint: tr(lang,
                en: 'Write a message…',
                ru: 'Напиши сообщение…',
                ky: 'Билдирүү жаз…'),
          ),
        ],
      ),
    );
  }
}

/// Doctor-only briefing pinned above the messages. Compact, pre-formatted
/// 30-second read written by `generateDoctorBrief`. Shows nothing while
/// the brief is still composing — the messages themselves are readable.
class _BriefCard extends StatelessWidget {
  final String brief;
  final String lang;
  const _BriefCard({required this.brief, required this.lang});

  @override
  Widget build(BuildContext context) {
    return Container(
      margin: const EdgeInsets.fromLTRB(12, 12, 12, 0),
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(
        color: AppColors.primary.withValues(alpha: 0.08),
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: AppColors.primary.withValues(alpha: 0.25)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              const Icon(Icons.auto_awesome,
                  size: 14, color: AppColors.primary),
              const SizedBox(width: 6),
              Text(
                tr(lang,
                    en: 'BRIEFING',
                    ru: 'СВОДКА',
                    ky: 'КЫСКАЧА'),
                style: const TextStyle(
                  fontSize: 10,
                  fontWeight: FontWeight.w800,
                  color: AppColors.primary,
                  letterSpacing: 0.6,
                ),
              ),
            ],
          ),
          const SizedBox(height: 6),
          Text(
            brief,
            style: const TextStyle(
              fontSize: 13,
              color: AppColors.textPrimary,
              height: 1.4,
            ),
          ),
        ],
      ),
    );
  }
}

/// AI follow-up pills rendered under the doctor's most recent message.
/// Each pill, on tap, becomes the parent's next outgoing message.
class _FollowUpPills extends StatelessWidget {
  final List<String> suggestions;
  final ValueChanged<String> onTap;
  final String lang;
  const _FollowUpPills({
    required this.suggestions,
    required this.onTap,
    required this.lang,
  });

  @override
  Widget build(BuildContext context) {
    if (suggestions.isEmpty) return const SizedBox.shrink();
    return Padding(
      padding: const EdgeInsets.fromLTRB(8, 6, 8, 10),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Padding(
            padding: const EdgeInsets.only(left: 6, bottom: 4),
            child: Text(
              tr(lang,
                  en: 'You might want to ask',
                  ru: 'Можно спросить',
                  ky: 'Сурасаңыз болот'),
              style: const TextStyle(
                color: AppColors.textHint,
                fontSize: 11,
                fontWeight: FontWeight.w700,
                letterSpacing: 0.4,
              ),
            ),
          ),
          Wrap(
            spacing: 6,
            runSpacing: 6,
            children: suggestions
                .map((q) => _FollowUpPill(text: q, onTap: () => onTap(q)))
                .toList(),
          ),
        ],
      ),
    );
  }
}

class _FollowUpPill extends StatelessWidget {
  final String text;
  final VoidCallback onTap;
  const _FollowUpPill({required this.text, required this.onTap});

  @override
  Widget build(BuildContext context) {
    return Material(
      color: AppColors.surface,
      borderRadius: BorderRadius.circular(20),
      child: InkWell(
        onTap: onTap,
        borderRadius: BorderRadius.circular(20),
        child: Container(
          padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
          decoration: BoxDecoration(
            border: Border.all(color: AppColors.primary.withValues(alpha: 0.4)),
            borderRadius: BorderRadius.circular(20),
          ),
          child: Text(
            text,
            style: const TextStyle(
              fontSize: 12,
              fontWeight: FontWeight.w600,
              color: AppColors.primary,
              height: 1.3,
            ),
          ),
        ),
      ),
    );
  }
}

class _Bubble extends StatelessWidget {
  final ConsultMessage message;
  final bool mine;
  const _Bubble({required this.message, required this.mine});

  @override
  Widget build(BuildContext context) {
    final bg = mine ? AppColors.primary : AppColors.surface;
    final fg = mine ? Colors.white : AppColors.textPrimary;
    return Align(
      alignment: mine ? Alignment.centerRight : Alignment.centerLeft,
      child: Container(
        constraints: BoxConstraints(
            maxWidth: MediaQuery.of(context).size.width * 0.78),
        margin: const EdgeInsets.symmetric(vertical: 4),
        padding: const EdgeInsets.all(11),
        decoration: BoxDecoration(
          color: bg,
          borderRadius: BorderRadius.circular(14),
          border: mine ? null : Border.all(color: AppColors.divider),
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            if (message.photoUrl != null) ...[
              ClipRRect(
                borderRadius: BorderRadius.circular(10),
                child: Image.network(message.photoUrl!,
                    width: 200, fit: BoxFit.cover,
                    errorBuilder: (_, _, _) => const SizedBox()),
              ),
              if (message.text.isNotEmpty) const SizedBox(height: 6),
            ],
            if (message.text.isNotEmpty)
              Text(message.text,
                  style: TextStyle(color: fg, fontSize: 14, height: 1.35)),
            const SizedBox(height: 3),
            Text(
              DateFormat.MMMd(Localizations.localeOf(context).toString())
                  .add_jm()
                  .format(message.createdAt),
              style: TextStyle(
                fontSize: 10,
                color: mine ? Colors.white70 : AppColors.textHint,
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class _Composer extends StatelessWidget {
  final TextEditingController controller;
  final bool sending;
  final VoidCallback onSend;
  final VoidCallback onAttach;
  final String hint;
  const _Composer({
    required this.controller,
    required this.sending,
    required this.onSend,
    required this.onAttach,
    required this.hint,
  });

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      top: false,
      child: Container(
        padding: const EdgeInsets.fromLTRB(8, 8, 8, 8),
        decoration: const BoxDecoration(
          color: AppColors.surface,
          border: Border(top: BorderSide(color: AppColors.divider)),
        ),
        child: Row(
          crossAxisAlignment: CrossAxisAlignment.end,
          children: [
            IconButton(
              icon: const Icon(Icons.add_photo_alternate_outlined,
                  color: AppColors.primary),
              onPressed: sending ? null : onAttach,
            ),
            Expanded(
              child: TextField(
                controller: controller,
                minLines: 1,
                maxLines: 5,
                textCapitalization: TextCapitalization.sentences,
                decoration: InputDecoration(
                  hintText: hint,
                  border: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(20),
                      borderSide:
                          const BorderSide(color: AppColors.divider)),
                  contentPadding: const EdgeInsets.symmetric(
                      horizontal: 16, vertical: 10),
                  isDense: true,
                ),
              ),
            ),
            const SizedBox(width: 4),
            IconButton(
              icon: sending
                  ? const SizedBox(
                      height: 18,
                      width: 18,
                      child:
                          CircularProgressIndicator(strokeWidth: 2))
                  : const Icon(Icons.arrow_upward_rounded,
                      color: AppColors.primary),
              onPressed: sending ? null : onSend,
            ),
          ],
        ),
      ),
    );
  }
}
